<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>WinExe</OutputType>
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <CETCompat>false</CETCompat>
  </PropertyGroup>

  <PropertyGroup>
    <RobustCef Condition="'$(RobustCef)' == ''">true</RobustCef>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RobustCef)' == 'true'">
    <DefineConstants>$(DefineConstants);ROBUST_CEF</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup Condition="'$(RobustCef)' == 'true'">
    <PackageReference Include="Robust.Natives.Cef" />
    <ProjectReference Include="..\cefglue\CefGlue\CefGlue.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(RobustCef)' != 'true'">
    <Compile Remove="Cef\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Robust.Client\Robust.Client.csproj" />
    <ProjectReference Include="..\Robust.Shared.Maths\Robust.Shared.Maths.csproj" />
    <ProjectReference Include="..\Robust.Shared\Robust.Shared.csproj" />
  </ItemGroup>

  <Import Project="..\MSBuild\Robust.Properties.targets" />
</Project>
